import json
from pathlib import Path


RESULT_PATH = Path("devsentinel_result.json")
COMMENT_PATH = Path("devsentinel_pr_comment.md")


def build_comment(result: dict) -> str:
    """
    Builds a Markdown comment for GitHub PR.
    """

    decision = result.get("decision", "UNKNOWN")
    reason = result.get("reason", "No reason provided")
    findings = result.get("findings", [])

    status_icon = "✅" if decision == "ALLOW" else "❌"

    lines = [
        f"## {status_icon} DevSentinel Security Review: {decision}",
        "",
        f"**Reason:** {reason}",
        ""
    ]

    if findings:
        lines.append("### Findings")
        lines.append("")

        for finding in findings:
            lines.append(f"- **Type:** `{finding.get('type')}`")
            lines.append(f"  - **Severity:** {finding.get('severity')}")
            lines.append(f"  - **Action:** {finding.get('action')}")
            lines.append("")

        lines.append("### Required Developer Actions")
        lines.append("")
        lines.append("1. Remove the hardcoded secret from the code.")
        lines.append("2. Move the value to an environment variable or approved secret manager.")
        lines.append("3. Rotate the exposed credential immediately.")
        lines.append("4. Rerun the PR scan after fixing the issue.")
    else:
        lines.append("No hardcoded secrets were detected in this PR diff.")

    lines.append("")
    lines.append("---")
    lines.append("_Generated by DevSentinel AI Security Copilot_")

    return "\n".join(lines)


def main() -> None:
    if not RESULT_PATH.exists():
        raise FileNotFoundError("devsentinel_result.json not found")

    result = json.loads(RESULT_PATH.read_text(encoding="utf-8"))
    comment = build_comment(result)

    COMMENT_PATH.write_text(comment, encoding="utf-8")
    print(comment)


if __name__ == "__main__":
    main()