import json
import sys
from pathlib import Path

try:
    from .main import run_devsentinel
    from .redactor import redact_secrets
except ImportError:
    from main import run_devsentinel
    from redactor import redact_secrets


RESULT_PATH = Path("devsentinel_result.json")
REDACTED_DIFF_PATH = Path("devsentinel_redacted_diff.txt")


def read_diff_file(diff_file_path: str) -> str:
    """
    Reads a PR diff file generated by GitHub Actions.
    """
    path = Path(diff_file_path)

    if not path.exists():
        raise FileNotFoundError(f"Diff file not found: {diff_file_path}")

    return path.read_text(encoding="utf-8")


def write_result_file(result: dict) -> None:
    """
    Writes scan result to devsentinel_result.json for GitHub Actions PR comments.
    """
    RESULT_PATH.write_text(json.dumps(result, indent=2), encoding="utf-8")


def write_redacted_diff(diff_text: str) -> None:
    """
    Writes a redacted copy of the PR diff for safe debugging and review.
    """
    redacted_text = redact_secrets(diff_text)
    REDACTED_DIFF_PATH.write_text(redacted_text, encoding="utf-8")


def print_pr_scan_result(result: dict) -> None:
    """
    Prints PR scan result in a readable CI-friendly format.
    """
    print("\nDevSentinel PR Scanner")
    print("----------------------")
    print(f"SCAN: {result.get('source')}")

    if result.get("decision") == "BLOCK":
        print(f"BLOCK: {result.get('reason')}")

        for finding in result.get("findings", []):
            print(f"  - Type: {finding.get('type')}")
            print(f"    Severity: {finding.get('severity')}")
            print(f"    Action: {finding.get('action')}")
    else:
        print(f"ALLOW: {result.get('reason')}")

    print(f"\nRedacted diff written to: {REDACTED_DIFF_PATH}")


def main() -> int:
    """
    Runs DevSentinel against a PR diff file.

    Return codes:
    - 0 means ALLOW / pass CI
    - 1 means BLOCK / fail CI
    """

    if len(sys.argv) < 2:
        print("Usage: python -m app.pr_scanner <diff_file_path>")
        return 1

    diff_file_path = sys.argv[1]
    query = "Review this pull request diff before merge."

    diff_text = read_diff_file(diff_file_path)

    # Redact raw secret values before creating any safe debug artifact.
    write_redacted_diff(diff_text)

    result = run_devsentinel(
        query=query,
        diff_text=diff_text,
        source_name=diff_file_path
    )

    write_result_file(result)
    print_pr_scan_result(result)

    if result["decision"] == "BLOCK":
        print("\nDevSentinel decision: BLOCK")
        return 1

    print("\nDevSentinel decision: ALLOW")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())