import sys
from pathlib import Path

try:
    from .main import run_devsentinel
except ImportError:
    from main import run_devsentinel


def read_diff_file(diff_file_path: str) -> str:
    """
    Reads a PR diff file generated by GitHub Actions.
    """
    path = Path(diff_file_path)

    if not path.exists():
        raise FileNotFoundError(f"Diff file not found: {diff_file_path}")

    return path.read_text(encoding="utf-8")


def print_pr_scan_result(result: dict) -> None:
    """
    Prints PR scan result in a readable CI-friendly format.
    """
    print("\nDevSentinel PR Scanner")
    print("----------------------")
    print(f"SCAN: {result.get('source')}")

    if result.get("decision") == "BLOCK":
        print(f"BLOCK: {result.get('reason')}")

        for finding in result.get("findings", []):
            print(f"  - Type: {finding.get('type')}")
            print(f"    Severity: {finding.get('severity')}")
            print(f"    Action: {finding.get('action')}")
    else:
        print(f"ALLOW: {result.get('reason')}")


def main() -> int:
    """
    Runs DevSentinel against a PR diff file.

    Return codes:
    - 0 means ALLOW / pass CI
    - 1 means BLOCK / fail CI
    """

    if len(sys.argv) < 2:
        print("Usage: python -m app.pr_scanner <diff_file_path>")
        return 1

    diff_file_path = sys.argv[1]
    query = "Review this pull request diff before merge."

    diff_text = read_diff_file(diff_file_path)

    result = run_devsentinel(
        query=query,
        diff_text=diff_text,
        source_name=diff_file_path
    )

    print_pr_scan_result(result)

    if result["decision"] == "BLOCK":
        print("\nDevSentinel decision: BLOCK")
        return 1

    print("\nDevSentinel decision: ALLOW")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())